# Generated by Django 4.1.6 on 2023-02-14 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prompt', models.CharField(max_length=250)),
                ('is_continuous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoricalVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.variable')),
                ('is_binary', models.BooleanField(default=True)),
                ('choices', models.CharField(max_length=500)),
            ],
            bases=('backend.variable',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Required. Enter your email.', max_length=254, unique=True)),
                ('number', models.CharField(help_text='Enter your phone number.', max_length=11)),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Non binary', 'Non binary'), ('Other', 'Other')], default='Woman', max_length=20)),
                ('dob', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('variables', models.ManyToManyField(related_name='users', to='backend.variable')),
            ],
        ),
    ]
